packages:
  - contracts

ignoredBuiltDependencies:
  - esbuild
  - prisma-zod-generator
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - prisma
  - unrs-resolver
