import { PrismaClient } from '@prisma/client';
import { ALL_PERMISSIONS } from '../src/modules/auth/permissions';

const prisma = new PrismaClient();

const COUNTRIES: { code: string; currency: string }[] = [
  { code: 'AC', currency: 'SHP' },
  { code: 'AD', currency: 'EUR' },
  { code: 'AE', currency: 'AED' },
  { code: 'AF', currency: 'AFN' },
  { code: 'AG', currency: 'XCD' },
  { code: 'AI', currency: 'XCD' },
  { code: 'AL', currency: 'ALL' },
  { code: 'AM', currency: 'AMD' },
  { code: 'AO', currency: 'AOA' },
  { code: 'AR', currency: 'ARS' },
  { code: 'AS', currency: 'USD' },
  { code: 'AT', currency: 'EUR' },
  { code: 'AU', currency: 'AUD' },
  { code: 'AW', currency: 'AWG' },
  { code: 'AX', currency: 'EUR' },
  { code: 'AZ', currency: 'AZN' },
  { code: 'BA', currency: 'BAM' },
  { code: 'BB', currency: 'BBD' },
  { code: 'BD', currency: 'BDT' },
  { code: 'BE', currency: 'EUR' },
  { code: 'BF', currency: 'XOF' },
  { code: 'BG', currency: 'BGN' },
  { code: 'BH', currency: 'BHD' },
  { code: 'BI', currency: 'BIF' },
  { code: 'BJ', currency: 'XOF' },
  { code: 'BL', currency: 'EUR' },
  { code: 'BM', currency: 'BMD' },
  { code: 'BN', currency: 'BND' },
  { code: 'BO', currency: 'BOB' },
  { code: 'BQ', currency: 'USD' },
  { code: 'BR', currency: 'BRL' },
  { code: 'BS', currency: 'BSD' },
  { code: 'BT', currency: 'BTN' },
  { code: 'BV', currency: 'NOK' },
  { code: 'BW', currency: 'BWP' },
  { code: 'BY', currency: 'BYN' },
  { code: 'BZ', currency: 'BZD' },
  { code: 'CA', currency: 'CAD' },
  { code: 'CC', currency: 'AUD' },
  { code: 'CD', currency: 'CDF' },
  { code: 'CF', currency: 'XAF' },
  { code: 'CG', currency: 'XAF' },
  { code: 'CH', currency: 'CHF' },
  { code: 'CI', currency: 'XOF' },
  { code: 'CK', currency: 'NZD' },
  { code: 'CL', currency: 'CLP' },
  { code: 'CM', currency: 'XAF' },
  { code: 'CN', currency: 'CNY' },
  { code: 'CO', currency: 'COP' },
  { code: 'CR', currency: 'CRC' },
  { code: 'CU', currency: 'CUP' },
  { code: 'CV', currency: 'CVE' },
  { code: 'CW', currency: 'ANG' },
  { code: 'CX', currency: 'AUD' },
  { code: 'CY', currency: 'EUR' },
  { code: 'CZ', currency: 'CZK' },
  { code: 'DE', currency: 'EUR' },
  { code: 'DG', currency: 'USD' },
  { code: 'DJ', currency: 'DJF' },
  { code: 'DK', currency: 'DKK' },
  { code: 'DM', currency: 'XCD' },
  { code: 'DO', currency: 'DOP' },
  { code: 'DZ', currency: 'DZD' },
  { code: 'EA', currency: 'EUR' },
  { code: 'EC', currency: 'USD' },
  { code: 'EE', currency: 'EUR' },
  { code: 'EG', currency: 'EGP' },
  { code: 'EH', currency: 'MAD' },
  { code: 'ER', currency: 'ERN' },
  { code: 'ES', currency: 'EUR' },
  { code: 'ET', currency: 'ETB' },
  { code: 'EU', currency: 'EUR' },
  { code: 'FI', currency: 'EUR' },
  { code: 'FJ', currency: 'FJD' },
  { code: 'FK', currency: 'FKP' },
  { code: 'FM', currency: 'USD' },
  { code: 'FO', currency: 'DKK' },
  { code: 'FR', currency: 'EUR' },
  { code: 'GA', currency: 'XAF' },
  { code: 'GB', currency: 'GBP' },
  { code: 'GD', currency: 'XCD' },
  { code: 'GE', currency: 'GEL' },
  { code: 'GF', currency: 'EUR' },
  { code: 'GG', currency: 'GBP' },
  { code: 'GH', currency: 'GHS' },
  { code: 'GI', currency: 'GIP' },
  { code: 'GL', currency: 'DKK' },
  { code: 'GM', currency: 'GMD' },
  { code: 'GN', currency: 'GNF' },
  { code: 'GP', currency: 'EUR' },
  { code: 'GQ', currency: 'XAF' },
  { code: 'GR', currency: 'EUR' },
  { code: 'GS', currency: 'GBP' },
  { code: 'GT', currency: 'GTQ' },
  { code: 'GU', currency: 'USD' },
  { code: 'GW', currency: 'XOF' },
  { code: 'GY', currency: 'GYD' },
  { code: 'HK', currency: 'HKD' },
  { code: 'HM', currency: 'AUD' },
  { code: 'HN', currency: 'HNL' },
  { code: 'HR', currency: 'EUR' },
  { code: 'HT', currency: 'HTG' },
  { code: 'HU', currency: 'HUF' },
  { code: 'IC', currency: 'EUR' },
  { code: 'ID', currency: 'IDR' },
  { code: 'IE', currency: 'EUR' },
  { code: 'IL', currency: 'ILS' },
  { code: 'IM', currency: 'GBP' },
  { code: 'IN', currency: 'INR' },
  { code: 'IO', currency: 'USD' },
  { code: 'IQ', currency: 'IQD' },
  { code: 'IR', currency: 'IRR' },
  { code: 'IS', currency: 'ISK' },
  { code: 'IT', currency: 'EUR' },
  { code: 'JE', currency: 'GBP' },
  { code: 'JM', currency: 'JMD' },
  { code: 'JO', currency: 'JOD' },
  { code: 'JP', currency: 'JPY' },
  { code: 'KE', currency: 'KES' },
  { code: 'KG', currency: 'KGS' },
  { code: 'KH', currency: 'KHR' },
  { code: 'KI', currency: 'AUD' },
  { code: 'KM', currency: 'KMF' },
  { code: 'KN', currency: 'XCD' },
  { code: 'KP', currency: 'KPW' },
  { code: 'KR', currency: 'KRW' },
  { code: 'KW', currency: 'KWD' },
  { code: 'KY', currency: 'KYD' },
  { code: 'KZ', currency: 'KZT' },
  { code: 'LA', currency: 'LAK' },
  { code: 'LB', currency: 'LBP' },
  { code: 'LC', currency: 'XCD' },
  { code: 'LI', currency: 'CHF' },
  { code: 'LK', currency: 'LKR' },
  { code: 'LR', currency: 'LRD' },
  { code: 'LS', currency: 'LSL' },
  { code: 'LT', currency: 'EUR' },
  { code: 'LU', currency: 'EUR' },
  { code: 'LV', currency: 'EUR' },
  { code: 'LY', currency: 'LYD' },
  { code: 'MA', currency: 'MAD' },
  { code: 'MC', currency: 'EUR' },
  { code: 'MD', currency: 'MDL' },
  { code: 'ME', currency: 'EUR' },
  { code: 'MF', currency: 'EUR' },
  { code: 'MG', currency: 'MGA' },
  { code: 'MH', currency: 'USD' },
  { code: 'MK', currency: 'MKD' },
  { code: 'ML', currency: 'XOF' },
  { code: 'MM', currency: 'MMK' },
  { code: 'MN', currency: 'MNT' },
  { code: 'MO', currency: 'MOP' },
  { code: 'MP', currency: 'USD' },
  { code: 'MQ', currency: 'EUR' },
  { code: 'MR', currency: 'MRU' },
  { code: 'MS', currency: 'XCD' },
  { code: 'MT', currency: 'EUR' },
  { code: 'MU', currency: 'MUR' },
  { code: 'MV', currency: 'MVR' },
  { code: 'MW', currency: 'MWK' },
  { code: 'MX', currency: 'MXN' },
  { code: 'MY', currency: 'MYR' },
  { code: 'MZ', currency: 'MZN' },
  { code: 'NA', currency: 'NAD' },
  { code: 'NC', currency: 'XPF' },
  { code: 'NE', currency: 'XOF' },
  { code: 'NF', currency: 'AUD' },
  { code: 'NG', currency: 'NGN' },
  { code: 'NI', currency: 'NIO' },
  { code: 'NL', currency: 'EUR' },
  { code: 'NO', currency: 'NOK' },
  { code: 'NP', currency: 'NPR' },
  { code: 'NR', currency: 'AUD' },
  { code: 'NU', currency: 'NZD' },
  { code: 'NZ', currency: 'NZD' },
  { code: 'OM', currency: 'OMR' },
  { code: 'PA', currency: 'PAB' },
  { code: 'PE', currency: 'PEN' },
  { code: 'PF', currency: 'XPF' },
  { code: 'PG', currency: 'PGK' },
  { code: 'PH', currency: 'PHP' },
  { code: 'PK', currency: 'PKR' },
  { code: 'PL', currency: 'PLN' },
  { code: 'PM', currency: 'EUR' },
  { code: 'PN', currency: 'NZD' },
  { code: 'PR', currency: 'USD' },
  { code: 'PS', currency: 'ILS' },
  { code: 'PT', currency: 'EUR' },
  { code: 'PW', currency: 'USD' },
  { code: 'PY', currency: 'PYG' },
  { code: 'QA', currency: 'QAR' },
  { code: 'RE', currency: 'EUR' },
  { code: 'RO', currency: 'RON' },
  { code: 'RS', currency: 'RSD' },
  { code: 'RU', currency: 'RUB' },
  { code: 'RW', currency: 'RWF' },
  { code: 'SA', currency: 'SAR' },
  { code: 'SB', currency: 'SBD' },
  { code: 'SC', currency: 'SCR' },
  { code: 'SD', currency: 'SDG' },
  { code: 'SE', currency: 'SEK' },
  { code: 'SG', currency: 'SGD' },
  { code: 'SH', currency: 'SHP' },
  { code: 'SI', currency: 'EUR' },
  { code: 'SJ', currency: 'NOK' },
  { code: 'SK', currency: 'EUR' },
  { code: 'SL', currency: 'SLE' },
  { code: 'SM', currency: 'EUR' },
  { code: 'SN', currency: 'XOF' },
  { code: 'SO', currency: 'SOS' },
  { code: 'SR', currency: 'SRD' },
  { code: 'SS', currency: 'SSP' },
  { code: 'ST', currency: 'STN' },
  { code: 'SV', currency: 'USD' },
  { code: 'SX', currency: 'ANG' },
  { code: 'SY', currency: 'SYP' },
  { code: 'SZ', currency: 'SZL' },
  { code: 'TA', currency: 'SHP' },
  { code: 'TC', currency: 'USD' },
  { code: 'TD', currency: 'XAF' },
  { code: 'TF', currency: 'EUR' },
  { code: 'TG', currency: 'XOF' },
  { code: 'TH', currency: 'THB' },
  { code: 'TJ', currency: 'TJS' },
  { code: 'TK', currency: 'NZD' },
  { code: 'TL', currency: 'USD' },
  { code: 'TM', currency: 'TMT' },
  { code: 'TN', currency: 'TND' },
  { code: 'TO', currency: 'TOP' },
  { code: 'TR', currency: 'TRY' },
  { code: 'TT', currency: 'TTD' },
  { code: 'TV', currency: 'AUD' },
  { code: 'TW', currency: 'TWD' },
  { code: 'TZ', currency: 'TZS' },
  { code: 'UA', currency: 'UAH' },
  { code: 'UG', currency: 'UGX' },
  { code: 'UM', currency: 'USD' },
  { code: 'US', currency: 'USD' },
  { code: 'UY', currency: 'UYU' },
  { code: 'UZ', currency: 'UZS' },
  { code: 'VA', currency: 'EUR' },
  { code: 'VC', currency: 'XCD' },
  { code: 'VE', currency: 'VES' },
  { code: 'VG', currency: 'USD' },
  { code: 'VI', currency: 'USD' },
  { code: 'VN', currency: 'VND' },
  { code: 'VU', currency: 'VUV' },
  { code: 'WF', currency: 'XPF' },
  { code: 'WS', currency: 'WST' },
  { code: 'XK', currency: 'EUR' },
  { code: 'YE', currency: 'YER' },
  { code: 'YT', currency: 'EUR' },
  { code: 'ZA', currency: 'ZAR' },
  { code: 'ZM', currency: 'ZMW' },
  { code: 'ZW', currency: 'ZWL' },
];

async function main() {
  for (const country of COUNTRIES) {
    await prisma.country.upsert({
      where: { code: country.code },
      update: { currency: country.currency },
      create: country,
    });
  }

  for (const name of ALL_PERMISSIONS) {
    await prisma.employeePermission.upsert({
      where: { name },
      update: {},
      create: { name },
    });
  }

  const adminRole = await prisma.employeeRole.upsert({
    where: { name: 'superadmin' },
    update: { color: '#f43f5e' },
    create: { name: 'superadmin', color: '#f43f5e' },
  });

  const permissions = await prisma.employeePermission.findMany({
    where: { name: { in: [...ALL_PERMISSIONS] } },
  });

  for (const permission of permissions) {
    await prisma.employeeRolePermission.upsert({
      where: {
        employeeRoleId_employeePermissionId: {
          employeeRoleId: adminRole.id,
          employeePermissionId: permission.id,
        },
      },
      update: {},
      create: {
        employeeRoleId: adminRole.id,
        employeePermissionId: permission.id,
      },
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
