-- Keep templates created before SKU generation was implemented compatible with
-- the final token name.
UPDATE "product_type"
SET "sku_template" = regexp_replace(
    regexp_replace("sku_template", '\{counter\}', '{seq}', 'g'),
    '\{counter:([0-9]+)\}',
    '{seq:\1}',
    'g'
)
WHERE "sku_mode" = 'TEMPLATE'
  AND "sku_template" LIKE '%{counter%';

-- Brand-derived SKUs were never generated by the backend. They cannot be
-- migrated safely after removing the mutable brand token, so fall back to the
-- deterministic global sequence and let an administrator configure a new
-- characteristic-based template explicitly.
UPDATE "product_type"
SET
    "sku_mode" = 'SEQUENTIAL',
    "sku_template" = NULL,
    "updated_at" = CURRENT_TIMESTAMP
WHERE "sku_mode" = 'TEMPLATE'
  AND "sku_template" ~ '\{brand(?::[0-9]+)?\}';
